export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_CONTACTS_START = "FETCH_CONTACTS_START";
export const FETCH_CONTACTS_FAIL = "FETCH_CONTACTS_FAIL";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";

export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";

export const CONTACT_LIST_CHANGE_INIT = "CONTACT_LIST_CHANGE_INIT";
export const CONTACT_LIST_CHANGE_FAIL = "CONTACT_LIST_CHANGE_FAIL";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";

export const FETCH_CARDS_START = "FETCH_CARDS_START";
export const FETCH_CARDS_FAIL = "FETCH_CARDS_FAIL";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";

export const CARD_LIST_CHANGE_INIT = "CARD_LIST_CHANGE_INIT";
export const CARD_LIST_CHANGE_FAIL = "CARD_LIST_CHANGE_FAIL";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const SEND_CARD_SUCCESS = "SEND_CARD_SUCCESS"

export const SELECT_CARD_CONTACT = "SELECT_CARD_CONTACT";
export const CANCEL_SELECT_CARD_CONTACT = "CANCEL_SELECT_CARD_CONTACT";

export const ERROR_HANDLE = "ERROR_HANDLE";
export const MESSAGE_HANDLE = "MESSAGE_HANDLE";
